version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/demo
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    mode: 777
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 10
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 10
      runas: ec2-user
